
services:
  bot:
    build: .
    container_name: profitbag_bot
    environment:
      DATABASE_URL: ${DATABASE_URL}
      BOT_TOKEN: ${BOT_TOKEN}
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: profitbag_db
    environment:
      POSTGRES_USER: stanislav
      POSTGRES_PASSWORD: secret_password
      POSTGRES_DB: profitbag
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
